steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME', '.']
images: ['gcr.io/$PROJECT_ID/$_IMAGE_NAME']
timeout: '1h'
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 20
substitutions:
  _IMAGE_NAME: 'notebook'
