steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$IMAGE_NAME', '.']
images: ['gcr.io/$PROJECT_ID/$IMAGE_NAME']
timeout: '1h'
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 20
