---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: storage
        persistentVolumeClaim:
          claimName: notebook-storage
          readOnly: false
      containers:
      - image: ghcr.io/n1mmy/notebook:latest
        name: notebook
        env:
        # set a password: 'hi there'
        # echo -n 'your new password' | shasum
        - name: 'NOTEBOOK_EXTRA_ARGS'
          value: '--NotebookApp.password=sha1:56170f5429b35dea081bb659b884b475ca9329a9'
        ports:
        - containerPort: 8888
          name: notebook
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /root/notebooks
          name: storage
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            cpu: 1

